// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="edge_detect_hw_edge_detect_hw,hls_ip_2024_2_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=6.667000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=4.667000,HLS_SYN_LAT=7285487,HLS_SYN_TPT=none,HLS_SYN_MEM=468,HLS_SYN_DSP=0,HLS_SYN_FF=11359,HLS_SYN_LUT=11617,HLS_VERSION=2024_2_2}" *)

module edge_detect_hw (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 25'd1;
parameter    ap_ST_fsm_state2 = 25'd2;
parameter    ap_ST_fsm_state3 = 25'd4;
parameter    ap_ST_fsm_state4 = 25'd8;
parameter    ap_ST_fsm_state5 = 25'd16;
parameter    ap_ST_fsm_state6 = 25'd32;
parameter    ap_ST_fsm_state7 = 25'd64;
parameter    ap_ST_fsm_state8 = 25'd128;
parameter    ap_ST_fsm_state9 = 25'd256;
parameter    ap_ST_fsm_state10 = 25'd512;
parameter    ap_ST_fsm_state11 = 25'd1024;
parameter    ap_ST_fsm_state12 = 25'd2048;
parameter    ap_ST_fsm_state13 = 25'd4096;
parameter    ap_ST_fsm_state14 = 25'd8192;
parameter    ap_ST_fsm_state15 = 25'd16384;
parameter    ap_ST_fsm_state16 = 25'd32768;
parameter    ap_ST_fsm_state17 = 25'd65536;
parameter    ap_ST_fsm_state18 = 25'd131072;
parameter    ap_ST_fsm_state19 = 25'd262144;
parameter    ap_ST_fsm_state20 = 25'd524288;
parameter    ap_ST_fsm_state21 = 25'd1048576;
parameter    ap_ST_fsm_state22 = 25'd2097152;
parameter    ap_ST_fsm_state23 = 25'd4194304;
parameter    ap_ST_fsm_state24 = 25'd8388608;
parameter    ap_ST_fsm_state25 = 25'd16777216;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [24:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] image_gray;
wire   [63:0] output_r;
wire   [3:0] filter_addr_8_reg_299;
reg    ap_block_state1;
wire   [3:0] filter_addr_reg_305;
wire    ap_CS_fsm_state2;
wire   [3:0] filter_addr_1_reg_311;
wire   [3:0] filter_addr_2_reg_317;
wire    ap_CS_fsm_state3;
wire   [3:0] filter_addr_3_reg_323;
wire   [3:0] filter_addr_4_reg_329;
wire    ap_CS_fsm_state4;
wire   [3:0] filter_addr_5_reg_335;
wire   [3:0] filter_addr_6_reg_341;
wire    ap_CS_fsm_state5;
wire   [3:0] filter_addr_7_reg_347;
reg   [63:0] output_r_read_reg_353;
wire    ap_CS_fsm_state13;
reg   [63:0] image_gray_read_reg_361;
reg   [3:0] filter_address0;
reg    filter_ce0;
wire   [3:0] filter_q0;
reg   [17:0] temp_buf_address0;
reg    temp_buf_ce0;
reg    temp_buf_we0;
wire   [31:0] temp_buf_q0;
wire    grp_edge_detect_hw_Pipeline_1_fu_213_ap_start;
wire    grp_edge_detect_hw_Pipeline_1_fu_213_ap_done;
wire    grp_edge_detect_hw_Pipeline_1_fu_213_ap_idle;
wire    grp_edge_detect_hw_Pipeline_1_fu_213_ap_ready;
wire   [3:0] grp_edge_detect_hw_Pipeline_1_fu_213_filter_address0;
wire    grp_edge_detect_hw_Pipeline_1_fu_213_filter_ce0;
wire   [5:0] grp_edge_detect_hw_Pipeline_1_fu_213_normal_factor_1_out;
wire    grp_edge_detect_hw_Pipeline_1_fu_213_normal_factor_1_out_ap_vld;
wire    grp_edge_detect_hw_Pipeline_2_fu_219_ap_start;
wire    grp_edge_detect_hw_Pipeline_2_fu_219_ap_done;
wire    grp_edge_detect_hw_Pipeline_2_fu_219_ap_idle;
wire    grp_edge_detect_hw_Pipeline_2_fu_219_ap_ready;
wire    grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWVALID;
wire   [63:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWADDR;
wire   [0:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWID;
wire   [31:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWLEN;
wire   [2:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWSIZE;
wire   [1:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWBURST;
wire   [1:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWLOCK;
wire   [3:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWCACHE;
wire   [2:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWPROT;
wire   [3:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWQOS;
wire   [3:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWREGION;
wire   [0:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWUSER;
wire    grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WVALID;
wire   [31:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WDATA;
wire   [3:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WSTRB;
wire    grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WLAST;
wire   [0:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WID;
wire   [0:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WUSER;
wire    grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARVALID;
wire   [63:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARADDR;
wire   [0:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARID;
wire   [31:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARLEN;
wire   [2:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARSIZE;
wire   [1:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARBURST;
wire   [1:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARLOCK;
wire   [3:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARCACHE;
wire   [2:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARPROT;
wire   [3:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARQOS;
wire   [3:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARREGION;
wire   [0:0] grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARUSER;
wire    grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_RREADY;
wire    grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_BREADY;
wire    grp_edge_detect_hw_Pipeline_3_fu_230_ap_start;
wire    grp_edge_detect_hw_Pipeline_3_fu_230_ap_done;
wire    grp_edge_detect_hw_Pipeline_3_fu_230_ap_idle;
wire    grp_edge_detect_hw_Pipeline_3_fu_230_ap_ready;
wire   [3:0] grp_edge_detect_hw_Pipeline_3_fu_230_filter_address0;
wire    grp_edge_detect_hw_Pipeline_3_fu_230_filter_ce0;
wire   [5:0] grp_edge_detect_hw_Pipeline_3_fu_230_normal_factor_2_out;
wire    grp_edge_detect_hw_Pipeline_3_fu_230_normal_factor_2_out_ap_vld;
wire    grp_edge_detect_hw_Pipeline_4_fu_236_ap_start;
wire    grp_edge_detect_hw_Pipeline_4_fu_236_ap_done;
wire    grp_edge_detect_hw_Pipeline_4_fu_236_ap_idle;
wire    grp_edge_detect_hw_Pipeline_4_fu_236_ap_ready;
wire    grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWVALID;
wire   [63:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWADDR;
wire   [0:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWID;
wire   [31:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWLEN;
wire   [2:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWSIZE;
wire   [1:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWBURST;
wire   [1:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWLOCK;
wire   [3:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWCACHE;
wire   [2:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWPROT;
wire   [3:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWQOS;
wire   [3:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWREGION;
wire   [0:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWUSER;
wire    grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WVALID;
wire   [31:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WDATA;
wire   [3:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WSTRB;
wire    grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WLAST;
wire   [0:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WID;
wire   [0:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WUSER;
wire    grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARVALID;
wire   [63:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARADDR;
wire   [0:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARID;
wire   [31:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARLEN;
wire   [2:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARSIZE;
wire   [1:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARBURST;
wire   [1:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARLOCK;
wire   [3:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARCACHE;
wire   [2:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARPROT;
wire   [3:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARQOS;
wire   [3:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARREGION;
wire   [0:0] grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARUSER;
wire    grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_RREADY;
wire    grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_BREADY;
wire    grp_edge_detect_hw_Pipeline_5_fu_245_ap_start;
wire    grp_edge_detect_hw_Pipeline_5_fu_245_ap_done;
wire    grp_edge_detect_hw_Pipeline_5_fu_245_ap_idle;
wire    grp_edge_detect_hw_Pipeline_5_fu_245_ap_ready;
wire   [3:0] grp_edge_detect_hw_Pipeline_5_fu_245_filter_address0;
wire    grp_edge_detect_hw_Pipeline_5_fu_245_filter_ce0;
wire   [5:0] grp_edge_detect_hw_Pipeline_5_fu_245_normal_factor_3_out;
wire    grp_edge_detect_hw_Pipeline_5_fu_245_normal_factor_3_out_ap_vld;
wire    grp_edge_detect_hw_Pipeline_6_fu_251_ap_start;
wire    grp_edge_detect_hw_Pipeline_6_fu_251_ap_done;
wire    grp_edge_detect_hw_Pipeline_6_fu_251_ap_idle;
wire    grp_edge_detect_hw_Pipeline_6_fu_251_ap_ready;
wire    grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWVALID;
wire   [63:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWADDR;
wire   [0:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWID;
wire   [31:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWLEN;
wire   [2:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWSIZE;
wire   [1:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWBURST;
wire   [1:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWLOCK;
wire   [3:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWCACHE;
wire   [2:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWPROT;
wire   [3:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWQOS;
wire   [3:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWREGION;
wire   [0:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWUSER;
wire    grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_WVALID;
wire   [31:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_WDATA;
wire   [3:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_WSTRB;
wire    grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_WLAST;
wire   [0:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_WID;
wire   [0:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_WUSER;
wire    grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARVALID;
wire   [63:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARADDR;
wire   [0:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARID;
wire   [31:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARLEN;
wire   [2:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARSIZE;
wire   [1:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARBURST;
wire   [1:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARLOCK;
wire   [3:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARCACHE;
wire   [2:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARPROT;
wire   [3:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARQOS;
wire   [3:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARREGION;
wire   [0:0] grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARUSER;
wire    grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_RREADY;
wire    grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_BREADY;
wire   [17:0] grp_edge_detect_hw_Pipeline_6_fu_251_temp_buf_address0;
wire    grp_edge_detect_hw_Pipeline_6_fu_251_temp_buf_ce0;
wire    grp_edge_detect_hw_Pipeline_6_fu_251_temp_buf_we0;
wire   [31:0] grp_edge_detect_hw_Pipeline_6_fu_251_temp_buf_d0;
wire    grp_edge_detect_hw_Pipeline_7_fu_260_ap_start;
wire    grp_edge_detect_hw_Pipeline_7_fu_260_ap_done;
wire    grp_edge_detect_hw_Pipeline_7_fu_260_ap_idle;
wire    grp_edge_detect_hw_Pipeline_7_fu_260_ap_ready;
wire    grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWVALID;
wire   [63:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWADDR;
wire   [0:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWID;
wire   [31:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWLEN;
wire   [2:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWSIZE;
wire   [1:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWBURST;
wire   [1:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWLOCK;
wire   [3:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWCACHE;
wire   [2:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWPROT;
wire   [3:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWQOS;
wire   [3:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWREGION;
wire   [0:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWUSER;
wire    grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WVALID;
wire   [31:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WDATA;
wire   [3:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WSTRB;
wire    grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WLAST;
wire   [0:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WID;
wire   [0:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WUSER;
wire    grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARVALID;
wire   [63:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARADDR;
wire   [0:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARID;
wire   [31:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARLEN;
wire   [2:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARSIZE;
wire   [1:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARBURST;
wire   [1:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARLOCK;
wire   [3:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARCACHE;
wire   [2:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARPROT;
wire   [3:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARQOS;
wire   [3:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARREGION;
wire   [0:0] grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARUSER;
wire    grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_RREADY;
wire    grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_BREADY;
wire   [17:0] grp_edge_detect_hw_Pipeline_7_fu_260_temp_buf_address0;
wire    grp_edge_detect_hw_Pipeline_7_fu_260_temp_buf_ce0;
reg    gmem_0_AWVALID;
wire    gmem_0_AWREADY;
reg   [63:0] gmem_0_AWADDR;
reg   [31:0] gmem_0_AWLEN;
reg    gmem_0_WVALID;
wire    gmem_0_WREADY;
reg   [31:0] gmem_0_WDATA;
reg   [3:0] gmem_0_WSTRB;
reg    gmem_0_ARVALID;
wire    gmem_0_ARREADY;
reg   [63:0] gmem_0_ARADDR;
reg   [31:0] gmem_0_ARLEN;
wire    gmem_0_RVALID;
reg    gmem_0_RREADY;
wire   [31:0] gmem_0_RDATA;
wire   [8:0] gmem_0_RFIFONUM;
wire    gmem_0_BVALID;
reg    gmem_0_BREADY;
reg    grp_edge_detect_hw_Pipeline_1_fu_213_ap_start_reg;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
reg    grp_edge_detect_hw_Pipeline_2_fu_219_ap_start_reg;
wire    ap_CS_fsm_state14;
reg    grp_edge_detect_hw_Pipeline_3_fu_230_ap_start_reg;
reg    grp_edge_detect_hw_Pipeline_4_fu_236_ap_start_reg;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state21;
reg    grp_edge_detect_hw_Pipeline_5_fu_245_ap_start_reg;
reg    grp_edge_detect_hw_Pipeline_6_fu_251_ap_start_reg;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state23;
reg    grp_edge_detect_hw_Pipeline_7_fu_260_ap_start_reg;
reg   [24:0] ap_NS_fsm;
wire    ap_NS_fsm_state24;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
reg    filter_we0_local;
reg   [3:0] filter_d0_local;
reg    filter_ce0_local;
reg   [3:0] filter_address0_local;
reg    filter_we1_local;
reg   [3:0] filter_d1_local;
reg    filter_ce1_local;
reg   [3:0] filter_address1_local;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state19;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
reg    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_block_state14_on_subcall_done;
reg    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_block_state21_on_subcall_done;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
reg    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
reg    ap_ST_fsm_state25_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 25'd1;
#0 grp_edge_detect_hw_Pipeline_1_fu_213_ap_start_reg = 1'b0;
#0 grp_edge_detect_hw_Pipeline_2_fu_219_ap_start_reg = 1'b0;
#0 grp_edge_detect_hw_Pipeline_3_fu_230_ap_start_reg = 1'b0;
#0 grp_edge_detect_hw_Pipeline_4_fu_236_ap_start_reg = 1'b0;
#0 grp_edge_detect_hw_Pipeline_5_fu_245_ap_start_reg = 1'b0;
#0 grp_edge_detect_hw_Pipeline_6_fu_251_ap_start_reg = 1'b0;
#0 grp_edge_detect_hw_Pipeline_7_fu_260_ap_start_reg = 1'b0;
end

edge_detect_hw_filter_RAM_AUTO_1R1W #(
    .DataWidth( 4 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
filter_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(filter_address0),
    .ce0(filter_ce0),
    .we0(filter_we0_local),
    .d0(filter_d0_local),
    .q0(filter_q0),
    .address1(filter_address1_local),
    .ce1(filter_ce1_local),
    .we1(filter_we1_local),
    .d1(filter_d1_local)
);

edge_detect_hw_temp_buf_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 262144 ),
    .AddressWidth( 18 ))
temp_buf_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(temp_buf_address0),
    .ce0(temp_buf_ce0),
    .we0(temp_buf_we0),
    .d0(grp_edge_detect_hw_Pipeline_6_fu_251_temp_buf_d0),
    .q0(temp_buf_q0)
);

edge_detect_hw_edge_detect_hw_Pipeline_1 grp_edge_detect_hw_Pipeline_1_fu_213(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_edge_detect_hw_Pipeline_1_fu_213_ap_start),
    .ap_done(grp_edge_detect_hw_Pipeline_1_fu_213_ap_done),
    .ap_idle(grp_edge_detect_hw_Pipeline_1_fu_213_ap_idle),
    .ap_ready(grp_edge_detect_hw_Pipeline_1_fu_213_ap_ready),
    .filter_address0(grp_edge_detect_hw_Pipeline_1_fu_213_filter_address0),
    .filter_ce0(grp_edge_detect_hw_Pipeline_1_fu_213_filter_ce0),
    .filter_q0(filter_q0),
    .normal_factor_1_out(grp_edge_detect_hw_Pipeline_1_fu_213_normal_factor_1_out),
    .normal_factor_1_out_ap_vld(grp_edge_detect_hw_Pipeline_1_fu_213_normal_factor_1_out_ap_vld)
);

edge_detect_hw_edge_detect_hw_Pipeline_2 grp_edge_detect_hw_Pipeline_2_fu_219(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_edge_detect_hw_Pipeline_2_fu_219_ap_start),
    .ap_done(grp_edge_detect_hw_Pipeline_2_fu_219_ap_done),
    .ap_idle(grp_edge_detect_hw_Pipeline_2_fu_219_ap_idle),
    .ap_ready(grp_edge_detect_hw_Pipeline_2_fu_219_ap_ready),
    .m_axi_gmem_0_AWVALID(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(gmem_0_AWREADY),
    .m_axi_gmem_0_AWADDR(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(gmem_0_WREADY),
    .m_axi_gmem_0_WDATA(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(gmem_0_ARREADY),
    .m_axi_gmem_0_ARADDR(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(gmem_0_RVALID),
    .m_axi_gmem_0_RREADY(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(gmem_0_RDATA),
    .m_axi_gmem_0_RLAST(1'b0),
    .m_axi_gmem_0_RID(1'd0),
    .m_axi_gmem_0_RFIFONUM(gmem_0_RFIFONUM),
    .m_axi_gmem_0_RUSER(1'd0),
    .m_axi_gmem_0_RRESP(2'd0),
    .m_axi_gmem_0_BVALID(gmem_0_BVALID),
    .m_axi_gmem_0_BREADY(grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .image_gray(image_gray_read_reg_361),
    .normal_factor_1_reload(grp_edge_detect_hw_Pipeline_1_fu_213_normal_factor_1_out),
    .output_r(output_r_read_reg_353)
);

edge_detect_hw_edge_detect_hw_Pipeline_3 grp_edge_detect_hw_Pipeline_3_fu_230(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_edge_detect_hw_Pipeline_3_fu_230_ap_start),
    .ap_done(grp_edge_detect_hw_Pipeline_3_fu_230_ap_done),
    .ap_idle(grp_edge_detect_hw_Pipeline_3_fu_230_ap_idle),
    .ap_ready(grp_edge_detect_hw_Pipeline_3_fu_230_ap_ready),
    .filter_address0(grp_edge_detect_hw_Pipeline_3_fu_230_filter_address0),
    .filter_ce0(grp_edge_detect_hw_Pipeline_3_fu_230_filter_ce0),
    .filter_q0(filter_q0),
    .normal_factor_2_out(grp_edge_detect_hw_Pipeline_3_fu_230_normal_factor_2_out),
    .normal_factor_2_out_ap_vld(grp_edge_detect_hw_Pipeline_3_fu_230_normal_factor_2_out_ap_vld)
);

edge_detect_hw_edge_detect_hw_Pipeline_4 grp_edge_detect_hw_Pipeline_4_fu_236(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_edge_detect_hw_Pipeline_4_fu_236_ap_start),
    .ap_done(grp_edge_detect_hw_Pipeline_4_fu_236_ap_done),
    .ap_idle(grp_edge_detect_hw_Pipeline_4_fu_236_ap_idle),
    .ap_ready(grp_edge_detect_hw_Pipeline_4_fu_236_ap_ready),
    .m_axi_gmem_0_AWVALID(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(gmem_0_AWREADY),
    .m_axi_gmem_0_AWADDR(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(gmem_0_WREADY),
    .m_axi_gmem_0_WDATA(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(gmem_0_ARREADY),
    .m_axi_gmem_0_ARADDR(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(gmem_0_RVALID),
    .m_axi_gmem_0_RREADY(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(gmem_0_RDATA),
    .m_axi_gmem_0_RLAST(1'b0),
    .m_axi_gmem_0_RID(1'd0),
    .m_axi_gmem_0_RFIFONUM(gmem_0_RFIFONUM),
    .m_axi_gmem_0_RUSER(1'd0),
    .m_axi_gmem_0_RRESP(2'd0),
    .m_axi_gmem_0_BVALID(gmem_0_BVALID),
    .m_axi_gmem_0_BREADY(grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .output_r(output_r_read_reg_353),
    .normal_factor_2_reload(grp_edge_detect_hw_Pipeline_3_fu_230_normal_factor_2_out),
    .image_gray(image_gray_read_reg_361)
);

edge_detect_hw_edge_detect_hw_Pipeline_5 grp_edge_detect_hw_Pipeline_5_fu_245(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_edge_detect_hw_Pipeline_5_fu_245_ap_start),
    .ap_done(grp_edge_detect_hw_Pipeline_5_fu_245_ap_done),
    .ap_idle(grp_edge_detect_hw_Pipeline_5_fu_245_ap_idle),
    .ap_ready(grp_edge_detect_hw_Pipeline_5_fu_245_ap_ready),
    .filter_address0(grp_edge_detect_hw_Pipeline_5_fu_245_filter_address0),
    .filter_ce0(grp_edge_detect_hw_Pipeline_5_fu_245_filter_ce0),
    .filter_q0(filter_q0),
    .normal_factor_3_out(grp_edge_detect_hw_Pipeline_5_fu_245_normal_factor_3_out),
    .normal_factor_3_out_ap_vld(grp_edge_detect_hw_Pipeline_5_fu_245_normal_factor_3_out_ap_vld)
);

edge_detect_hw_edge_detect_hw_Pipeline_6 grp_edge_detect_hw_Pipeline_6_fu_251(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_edge_detect_hw_Pipeline_6_fu_251_ap_start),
    .ap_done(grp_edge_detect_hw_Pipeline_6_fu_251_ap_done),
    .ap_idle(grp_edge_detect_hw_Pipeline_6_fu_251_ap_idle),
    .ap_ready(grp_edge_detect_hw_Pipeline_6_fu_251_ap_ready),
    .m_axi_gmem_0_AWVALID(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(1'b0),
    .m_axi_gmem_0_AWADDR(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(1'b0),
    .m_axi_gmem_0_WDATA(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(gmem_0_ARREADY),
    .m_axi_gmem_0_ARADDR(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(gmem_0_RVALID),
    .m_axi_gmem_0_RREADY(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(gmem_0_RDATA),
    .m_axi_gmem_0_RLAST(1'b0),
    .m_axi_gmem_0_RID(1'd0),
    .m_axi_gmem_0_RFIFONUM(gmem_0_RFIFONUM),
    .m_axi_gmem_0_RUSER(1'd0),
    .m_axi_gmem_0_RRESP(2'd0),
    .m_axi_gmem_0_BVALID(1'b0),
    .m_axi_gmem_0_BREADY(grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .output_r(output_r_read_reg_353),
    .normal_factor_3_reload(grp_edge_detect_hw_Pipeline_5_fu_245_normal_factor_3_out),
    .temp_buf_address0(grp_edge_detect_hw_Pipeline_6_fu_251_temp_buf_address0),
    .temp_buf_ce0(grp_edge_detect_hw_Pipeline_6_fu_251_temp_buf_ce0),
    .temp_buf_we0(grp_edge_detect_hw_Pipeline_6_fu_251_temp_buf_we0),
    .temp_buf_d0(grp_edge_detect_hw_Pipeline_6_fu_251_temp_buf_d0)
);

edge_detect_hw_edge_detect_hw_Pipeline_7 grp_edge_detect_hw_Pipeline_7_fu_260(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_edge_detect_hw_Pipeline_7_fu_260_ap_start),
    .ap_done(grp_edge_detect_hw_Pipeline_7_fu_260_ap_done),
    .ap_idle(grp_edge_detect_hw_Pipeline_7_fu_260_ap_idle),
    .ap_ready(grp_edge_detect_hw_Pipeline_7_fu_260_ap_ready),
    .m_axi_gmem_0_AWVALID(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(gmem_0_AWREADY),
    .m_axi_gmem_0_AWADDR(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(gmem_0_WREADY),
    .m_axi_gmem_0_WDATA(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(gmem_0_ARREADY),
    .m_axi_gmem_0_ARADDR(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(gmem_0_RVALID),
    .m_axi_gmem_0_RREADY(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(gmem_0_RDATA),
    .m_axi_gmem_0_RLAST(1'b0),
    .m_axi_gmem_0_RID(1'd0),
    .m_axi_gmem_0_RFIFONUM(gmem_0_RFIFONUM),
    .m_axi_gmem_0_RUSER(1'd0),
    .m_axi_gmem_0_RRESP(2'd0),
    .m_axi_gmem_0_BVALID(gmem_0_BVALID),
    .m_axi_gmem_0_BREADY(grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .image_gray(image_gray_read_reg_361),
    .temp_buf_address0(grp_edge_detect_hw_Pipeline_7_fu_260_temp_buf_address0),
    .temp_buf_ce0(grp_edge_detect_hw_Pipeline_7_fu_260_temp_buf_ce0),
    .temp_buf_q0(temp_buf_q0),
    .output_r(output_r_read_reg_353)
);

edge_detect_hw_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .image_gray(image_gray),
    .output_r(output_r),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

edge_detect_hw_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 70 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_0_ARVALID),
    .I_CH0_ARREADY(gmem_0_ARREADY),
    .I_CH0_ARADDR(gmem_0_ARADDR),
    .I_CH0_ARLEN(gmem_0_ARLEN),
    .I_CH0_RVALID(gmem_0_RVALID),
    .I_CH0_RREADY(gmem_0_RREADY),
    .I_CH0_RDATA(gmem_0_RDATA),
    .I_CH0_RFIFONUM(gmem_0_RFIFONUM),
    .I_CH0_AWVALID(gmem_0_AWVALID),
    .I_CH0_AWREADY(gmem_0_AWREADY),
    .I_CH0_AWADDR(gmem_0_AWADDR),
    .I_CH0_AWLEN(gmem_0_AWLEN),
    .I_CH0_WVALID(gmem_0_WVALID),
    .I_CH0_WREADY(gmem_0_WREADY),
    .I_CH0_WDATA(gmem_0_WDATA),
    .I_CH0_WSTRB(gmem_0_WSTRB),
    .I_CH0_BVALID(gmem_0_BVALID),
    .I_CH0_BREADY(gmem_0_BREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((grp_edge_detect_hw_Pipeline_7_fu_260_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_edge_detect_hw_Pipeline_1_fu_213_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state6)) begin
            grp_edge_detect_hw_Pipeline_1_fu_213_ap_start_reg <= 1'b1;
        end else if ((grp_edge_detect_hw_Pipeline_1_fu_213_ap_ready == 1'b1)) begin
            grp_edge_detect_hw_Pipeline_1_fu_213_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_edge_detect_hw_Pipeline_2_fu_219_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_edge_detect_hw_Pipeline_2_fu_219_ap_start_reg <= 1'b1;
        end else if ((grp_edge_detect_hw_Pipeline_2_fu_219_ap_ready == 1'b1)) begin
            grp_edge_detect_hw_Pipeline_2_fu_219_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_edge_detect_hw_Pipeline_3_fu_230_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_edge_detect_hw_Pipeline_3_fu_230_ap_start_reg <= 1'b1;
        end else if ((grp_edge_detect_hw_Pipeline_3_fu_230_ap_ready == 1'b1)) begin
            grp_edge_detect_hw_Pipeline_3_fu_230_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_edge_detect_hw_Pipeline_4_fu_236_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state20)) begin
            grp_edge_detect_hw_Pipeline_4_fu_236_ap_start_reg <= 1'b1;
        end else if ((grp_edge_detect_hw_Pipeline_4_fu_236_ap_ready == 1'b1)) begin
            grp_edge_detect_hw_Pipeline_4_fu_236_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_edge_detect_hw_Pipeline_5_fu_245_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state20)) begin
            grp_edge_detect_hw_Pipeline_5_fu_245_ap_start_reg <= 1'b1;
        end else if ((grp_edge_detect_hw_Pipeline_5_fu_245_ap_ready == 1'b1)) begin
            grp_edge_detect_hw_Pipeline_5_fu_245_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_edge_detect_hw_Pipeline_6_fu_251_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state22)) begin
            grp_edge_detect_hw_Pipeline_6_fu_251_ap_start_reg <= 1'b1;
        end else if ((grp_edge_detect_hw_Pipeline_6_fu_251_ap_ready == 1'b1)) begin
            grp_edge_detect_hw_Pipeline_6_fu_251_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_edge_detect_hw_Pipeline_7_fu_260_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state24) & (1'b1 == ap_CS_fsm_state23))) begin
            grp_edge_detect_hw_Pipeline_7_fu_260_ap_start_reg <= 1'b1;
        end else if ((grp_edge_detect_hw_Pipeline_7_fu_260_ap_ready == 1'b1)) begin
            grp_edge_detect_hw_Pipeline_7_fu_260_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        image_gray_read_reg_361 <= image_gray;
        output_r_read_reg_353 <= output_r;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state14_on_subcall_done)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state21_on_subcall_done)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

always @ (*) begin
    if ((grp_edge_detect_hw_Pipeline_6_fu_251_ap_done == 1'b0)) begin
        ap_ST_fsm_state23_blk = 1'b1;
    end else begin
        ap_ST_fsm_state23_blk = 1'b0;
    end
end

assign ap_ST_fsm_state24_blk = 1'b0;

always @ (*) begin
    if ((grp_edge_detect_hw_Pipeline_7_fu_260_ap_done == 1'b0)) begin
        ap_ST_fsm_state25_blk = 1'b1;
    end else begin
        ap_ST_fsm_state25_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((grp_edge_detect_hw_Pipeline_1_fu_213_ap_done == 1'b0)) begin
        ap_ST_fsm_state7_blk = 1'b1;
    end else begin
        ap_ST_fsm_state7_blk = 1'b0;
    end
end

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((grp_edge_detect_hw_Pipeline_7_fu_260_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_edge_detect_hw_Pipeline_7_fu_260_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        filter_address0 = grp_edge_detect_hw_Pipeline_5_fu_245_filter_address0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        filter_address0 = grp_edge_detect_hw_Pipeline_3_fu_230_filter_address0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        filter_address0 = grp_edge_detect_hw_Pipeline_1_fu_213_filter_address0;
    end else begin
        filter_address0 = filter_address0_local;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state19)) begin
        filter_address0_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        filter_address0_local = filter_addr_6_reg_341;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        filter_address0_local = filter_addr_4_reg_329;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        filter_address0_local = filter_addr_2_reg_317;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        filter_address0_local = 64'd1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        filter_address0_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        filter_address0_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        filter_address0_local = filter_addr_1_reg_311;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        filter_address0_local = filter_addr_8_reg_299;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        filter_address0_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        filter_address0_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        filter_address0_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        filter_address0_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        filter_address0_local = 64'd0;
    end else begin
        filter_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        filter_address1_local = filter_addr_5_reg_335;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        filter_address1_local = filter_addr_3_reg_323;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        filter_address1_local = 64'd2;
    end else if ((1'b1 == ap_CS_fsm_state15)) begin
        filter_address1_local = 64'd0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        filter_address1_local = filter_addr_7_reg_347;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        filter_address1_local = 64'd7;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        filter_address1_local = 64'd5;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        filter_address1_local = 64'd3;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        filter_address1_local = filter_addr_reg_305;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        filter_address1_local = 64'd8;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        filter_address1_local = 64'd6;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        filter_address1_local = 64'd4;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        filter_address1_local = 64'd1;
    end else begin
        filter_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        filter_ce0 = grp_edge_detect_hw_Pipeline_5_fu_245_filter_ce0;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        filter_ce0 = grp_edge_detect_hw_Pipeline_3_fu_230_filter_ce0;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        filter_ce0 = grp_edge_detect_hw_Pipeline_1_fu_213_filter_ce0;
    end else begin
        filter_ce0 = filter_ce0_local;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        filter_ce0_local = 1'b1;
    end else begin
        filter_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        filter_ce1_local = 1'b1;
    end else begin
        filter_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state18)) begin
        filter_d0_local = 4'd14;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state10))) begin
        filter_d0_local = 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state9))) begin
        filter_d0_local = 4'd15;
    end else if (((1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3))) begin
        filter_d0_local = 4'd2;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state2))) begin
        filter_d0_local = 4'd1;
    end else begin
        filter_d0_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state12))) begin
        filter_d1_local = 4'd15;
    end else if ((1'b1 == ap_CS_fsm_state10)) begin
        filter_d1_local = 4'd14;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state8))) begin
        filter_d1_local = 4'd0;
    end else if (((1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4))) begin
        filter_d1_local = 4'd1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        filter_d1_local = 4'd4;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state2))) begin
        filter_d1_local = 4'd2;
    end else begin
        filter_d1_local = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1)))) begin
        filter_we0_local = 1'b1;
    end else begin
        filter_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2))) begin
        filter_we1_local = 1'b1;
    end else begin
        filter_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem_0_ARADDR = grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22))) begin
        gmem_0_ARADDR = grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_0_ARADDR = grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_0_ARADDR = grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARADDR;
    end else begin
        gmem_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem_0_ARLEN = grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22))) begin
        gmem_0_ARLEN = grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_0_ARLEN = grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_0_ARLEN = grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARLEN;
    end else begin
        gmem_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem_0_ARVALID = grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22))) begin
        gmem_0_ARVALID = grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_0_ARVALID = grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_0_ARVALID = grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_ARVALID;
    end else begin
        gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem_0_AWADDR = grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_0_AWADDR = grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWADDR;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_0_AWADDR = grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWADDR;
    end else begin
        gmem_0_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem_0_AWLEN = grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_0_AWLEN = grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWLEN;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_0_AWLEN = grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWLEN;
    end else begin
        gmem_0_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem_0_AWVALID = grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_0_AWVALID = grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_AWVALID;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_0_AWVALID = grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_AWVALID;
    end else begin
        gmem_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem_0_BREADY = grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_0_BREADY = grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_BREADY;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_0_BREADY = grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_BREADY;
    end else begin
        gmem_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem_0_RREADY = grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22))) begin
        gmem_0_RREADY = grp_edge_detect_hw_Pipeline_6_fu_251_m_axi_gmem_0_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_0_RREADY = grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_0_RREADY = grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_RREADY;
    end else begin
        gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem_0_WDATA = grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_0_WDATA = grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WDATA;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_0_WDATA = grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WDATA;
    end else begin
        gmem_0_WDATA = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem_0_WSTRB = grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_0_WSTRB = grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WSTRB;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_0_WSTRB = grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WSTRB;
    end else begin
        gmem_0_WSTRB = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24))) begin
        gmem_0_WVALID = grp_edge_detect_hw_Pipeline_7_fu_260_m_axi_gmem_0_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state20))) begin
        gmem_0_WVALID = grp_edge_detect_hw_Pipeline_4_fu_236_m_axi_gmem_0_WVALID;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state13))) begin
        gmem_0_WVALID = grp_edge_detect_hw_Pipeline_2_fu_219_m_axi_gmem_0_WVALID;
    end else begin
        gmem_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        temp_buf_address0 = grp_edge_detect_hw_Pipeline_7_fu_260_temp_buf_address0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        temp_buf_address0 = grp_edge_detect_hw_Pipeline_6_fu_251_temp_buf_address0;
    end else begin
        temp_buf_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        temp_buf_ce0 = grp_edge_detect_hw_Pipeline_7_fu_260_temp_buf_ce0;
    end else if ((1'b1 == ap_CS_fsm_state23)) begin
        temp_buf_ce0 = grp_edge_detect_hw_Pipeline_6_fu_251_temp_buf_ce0;
    end else begin
        temp_buf_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state23)) begin
        temp_buf_we0 = grp_edge_detect_hw_Pipeline_6_fu_251_temp_buf_we0;
    end else begin
        temp_buf_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (grp_edge_detect_hw_Pipeline_1_fu_213_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((1'b1 == ap_CS_fsm_state14) & (1'b0 == ap_block_state14_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((1'b1 == ap_CS_fsm_state21) & (1'b0 == ap_block_state21_on_subcall_done))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            if (((grp_edge_detect_hw_Pipeline_6_fu_251_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state23))) begin
                ap_NS_fsm = ap_ST_fsm_state24;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state23;
            end
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            if (((grp_edge_detect_hw_Pipeline_7_fu_260_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state25))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state25;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state24 = ap_NS_fsm[32'd23];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state14_on_subcall_done = ((grp_edge_detect_hw_Pipeline_3_fu_230_ap_done == 1'b0) | (grp_edge_detect_hw_Pipeline_2_fu_219_ap_done == 1'b0));
end

always @ (*) begin
    ap_block_state21_on_subcall_done = ((grp_edge_detect_hw_Pipeline_5_fu_245_ap_done == 1'b0) | (grp_edge_detect_hw_Pipeline_4_fu_236_ap_done == 1'b0));
end

assign filter_addr_1_reg_311 = 64'd2;

assign filter_addr_2_reg_317 = 64'd3;

assign filter_addr_3_reg_323 = 64'd4;

assign filter_addr_4_reg_329 = 64'd5;

assign filter_addr_5_reg_335 = 64'd6;

assign filter_addr_6_reg_341 = 64'd7;

assign filter_addr_7_reg_347 = 64'd8;

assign filter_addr_8_reg_299 = 64'd0;

assign filter_addr_reg_305 = 64'd1;

assign grp_edge_detect_hw_Pipeline_1_fu_213_ap_start = grp_edge_detect_hw_Pipeline_1_fu_213_ap_start_reg;

assign grp_edge_detect_hw_Pipeline_2_fu_219_ap_start = grp_edge_detect_hw_Pipeline_2_fu_219_ap_start_reg;

assign grp_edge_detect_hw_Pipeline_3_fu_230_ap_start = grp_edge_detect_hw_Pipeline_3_fu_230_ap_start_reg;

assign grp_edge_detect_hw_Pipeline_4_fu_236_ap_start = grp_edge_detect_hw_Pipeline_4_fu_236_ap_start_reg;

assign grp_edge_detect_hw_Pipeline_5_fu_245_ap_start = grp_edge_detect_hw_Pipeline_5_fu_245_ap_start_reg;

assign grp_edge_detect_hw_Pipeline_6_fu_251_ap_start = grp_edge_detect_hw_Pipeline_6_fu_251_ap_start_reg;

assign grp_edge_detect_hw_Pipeline_7_fu_260_ap_start = grp_edge_detect_hw_Pipeline_7_fu_260_ap_start_reg;

endmodule //edge_detect_hw
