// ==============================================================
// Generated by Vitis HLS v2024.2.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module edge_detect_hw_edge_detect_hw_Pipeline_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        filter_address0,
        filter_ce0,
        filter_q0,
        normal_factor_1_out,
        normal_factor_1_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] filter_address0;
output   filter_ce0;
input  [3:0] filter_q0;
output  [5:0] normal_factor_1_out;
output   normal_factor_1_out_ap_vld;

reg ap_idle;
reg normal_factor_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln166_fu_99_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln170_fu_173_p1;
wire    ap_block_pp0_stage0;
reg   [5:0] normal_factor_1_fu_40;
wire   [5:0] normal_factor_fu_230_p2;
wire    ap_loop_init;
reg   [1:0] c_fu_44;
wire   [1:0] add_ln167_fu_178_p2;
reg   [1:0] ap_sig_allocacmp_c_load;
reg   [1:0] r_fu_48;
wire   [1:0] select_ln166_fu_137_p3;
reg   [1:0] ap_sig_allocacmp_r_load;
reg   [3:0] indvar_flatten_fu_52;
wire   [3:0] add_ln166_fu_105_p2;
reg   [3:0] ap_sig_allocacmp_indvar_flatten_load;
wire    ap_block_pp0_stage0_01001;
reg    filter_ce0_local;
wire   [0:0] icmp_ln167_fu_117_p2;
wire   [1:0] add_ln166_1_fu_131_p2;
wire   [3:0] p_shl_fu_149_p3;
wire   [3:0] zext_ln166_fu_145_p1;
wire   [1:0] select_ln157_fu_123_p3;
wire   [3:0] zext_ln167_fu_163_p1;
wire   [3:0] empty_fu_157_p2;
wire   [3:0] add_ln170_fu_167_p2;
wire   [2:0] empty_43_fu_202_p1;
wire   [0:0] abscond_fu_212_p2;
wire   [2:0] neg_fu_206_p2;
wire   [2:0] p_d0_0_fu_218_p3;
wire   [5:0] zext_ln168_fu_226_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 normal_factor_1_fu_40 = 6'd0;
#0 c_fu_44 = 2'd0;
#0 r_fu_48 = 2'd0;
#0 indvar_flatten_fu_52 = 4'd0;
#0 ap_done_reg = 1'b0;
end

edge_detect_hw_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln166_fu_99_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_44 <= add_ln167_fu_178_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_44 <= 2'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln166_fu_99_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_52 <= add_ln166_fu_105_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_52 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            normal_factor_1_fu_40 <= 6'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            normal_factor_1_fu_40 <= normal_factor_fu_230_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln166_fu_99_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            r_fu_48 <= select_ln166_fu_137_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            r_fu_48 <= 2'd0;
        end
    end
end

always @ (*) begin
    if (((icmp_ln166_fu_99_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 2'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_44;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 4'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_52;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_r_load = 2'd0;
    end else begin
        ap_sig_allocacmp_r_load = r_fu_48;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filter_ce0_local = 1'b1;
    end else begin
        filter_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln166_fu_99_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        normal_factor_1_out_ap_vld = 1'b1;
    end else begin
        normal_factor_1_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign abscond_fu_212_p2 = (($signed(filter_q0) > $signed(4'd0)) ? 1'b1 : 1'b0);

assign add_ln166_1_fu_131_p2 = (ap_sig_allocacmp_r_load + 2'd1);

assign add_ln166_fu_105_p2 = (ap_sig_allocacmp_indvar_flatten_load + 4'd1);

assign add_ln167_fu_178_p2 = (select_ln157_fu_123_p3 + 2'd1);

assign add_ln170_fu_167_p2 = (zext_ln167_fu_163_p1 + empty_fu_157_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign empty_43_fu_202_p1 = filter_q0[2:0];

assign empty_fu_157_p2 = (p_shl_fu_149_p3 - zext_ln166_fu_145_p1);

assign filter_address0 = zext_ln170_fu_173_p1;

assign filter_ce0 = filter_ce0_local;

assign icmp_ln166_fu_99_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln167_fu_117_p2 = ((ap_sig_allocacmp_c_load == 2'd3) ? 1'b1 : 1'b0);

assign neg_fu_206_p2 = (3'd0 - empty_43_fu_202_p1);

assign normal_factor_1_out = normal_factor_1_fu_40;

assign normal_factor_fu_230_p2 = (zext_ln168_fu_226_p1 + normal_factor_1_fu_40);

assign p_d0_0_fu_218_p3 = ((abscond_fu_212_p2[0:0] == 1'b1) ? empty_43_fu_202_p1 : neg_fu_206_p2);

assign p_shl_fu_149_p3 = {{select_ln166_fu_137_p3}, {2'd0}};

assign select_ln157_fu_123_p3 = ((icmp_ln167_fu_117_p2[0:0] == 1'b1) ? 2'd0 : ap_sig_allocacmp_c_load);

assign select_ln166_fu_137_p3 = ((icmp_ln167_fu_117_p2[0:0] == 1'b1) ? add_ln166_1_fu_131_p2 : ap_sig_allocacmp_r_load);

assign zext_ln166_fu_145_p1 = select_ln166_fu_137_p3;

assign zext_ln167_fu_163_p1 = select_ln157_fu_123_p3;

assign zext_ln168_fu_226_p1 = p_d0_0_fu_218_p3;

assign zext_ln170_fu_173_p1 = add_ln170_fu_167_p2;

endmodule //edge_detect_hw_edge_detect_hw_Pipeline_1
